# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: ch.myorganization.fhir
canonical: http://myorganization.ch/fhir
name: WorkshopIG
status: draft
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2021+
releaseLabel: ci-build
publisher:
  name: My Organization
  url: http://myorganization.ch/kontakt

# ----- Set more IG configuration -----
title: "Workshop IG (R4)"
description: An example IG for the workshop about authoring a FSH IG
# https://www.hl7.org/fhir/valueset-spdx-license.html
license: CC-BY-SA-4.0

# ----- Set dependencies -----
dependencies:
  ch.fhir.ig.ch-core: 4.0.1
  hl7.terminology: 5.5.0

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
# ----- Define IG tabs (page content) -----
menu:
  Home: index.html
  Use Case: 
    German: usecase-german.html
  Profiles: profiles.html
  Artifacts: artifacts.html

# ----- Define own titles (default: IG Publisher generates titles) -----
pages:
  index.md:
    title: Home
  usecase-german.md:
    title: Anwendungsfälle
  profiles.md:
